"""
main.py

Why this file exists:
    This is the ENTRY POINT of our Python AI service.
    It runs a FastAPI web server that listens for requests from Node.js.

    Responsibilities:
    1. Define the /generate endpoint
    2. Receive two images from Node.js (person + garment)
    3. Call our generate.py to process the images
    4. Return the resulting image back to Node.js

    What is FastAPI?
    - FastAPI is a modern Python web framework (like Express for Node.js)
    - It's fast, has automatic type checking, and generates API docs
    - It runs on uvicorn (an async web server)

    How to start this server:
        pip install -r requirements.txt
        uvicorn main:app --reload --port 8000

    The --reload flag means the server auto-restarts when you change code.
    This is like nodemon for Python.

    API Documentation (auto-generated by FastAPI):
        http://localhost:8000/docs   ← interactive API docs
        http://localhost:8000/redoc  ← alternative docs
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import Response
import uvicorn

from generate import generate_tryon_image


# Create the FastAPI application
# The title and description show up in the auto-generated /docs page
app = FastAPI(
    title="VirtualFit AI Service",
    description="Generates virtual try-on images. Accepts person + garment images, returns composite result.",
    version="1.0.0 (Phase 3 — Placeholder)",
)


# ── Health Check Endpoint ─────────────────────────────────────────────────────
@app.get("/health")
async def health_check():
    """
    GET /health

    Why it exists:
        A simple endpoint to verify the Python service is running.
        Node.js can call this to check if the AI service is available.

    Test with:
        curl http://localhost:8000/health

    Output:
        { "status": "ok", "message": "..." }
    """
    return {
        "status": "ok",
        "message": "VirtualFit Python AI Service is running",
        "phase": "Phase 3 — Placeholder (real AI coming in Phase 4)",
    }


# ── Main Generate Endpoint ────────────────────────────────────────────────────
@app.post("/generate")
async def generate_endpoint(
    person_image: UploadFile = File(..., description="Full-body photo of the person"),
    garment_image: UploadFile = File(..., description="Photo of the garment to try on"),
):
    """
    POST /generate

    Why it exists:
        This is the core endpoint. Node.js calls this with two images
        and we return a generated try-on result image.

    Input (multipart/form-data):
        person_image  - the person's uploaded photo
        garment_image - the selected garment photo

    Output:
        image/png — the generated try-on image

    Test with curl:
        curl -X POST http://localhost:8000/generate \\
          -F "person_image=@/path/to/person.jpg" \\
          -F "garment_image=@/path/to/garment.png" \\
          --output result.png

    Error responses:
        422 - Missing or invalid files
        500 - Generation failed
    """

    # ── Read the uploaded files into memory ────────────────────────────────────
    # UploadFile.read() is async (note the 'await') because reading files
    # shouldn't block the server while it's processing other requests.
    try:
        person_image_bytes = await person_image.read()
        garment_image_bytes = await garment_image.read()
    except Exception as read_error:
        raise HTTPException(
            status_code=400,
            detail=f"Failed to read uploaded files: {str(read_error)}"
        )

    # ── Validate that we received actual data ─────────────────────────────────
    if not person_image_bytes:
        raise HTTPException(status_code=400, detail="Person image is empty.")

    if not garment_image_bytes:
        raise HTTPException(status_code=400, detail="Garment image is empty.")

    # ── Generate the try-on image ─────────────────────────────────────────────
    # This calls our generate.py module.
    # In Phase 4, this is where the real AI model will run.
    try:
        result_image_bytes = generate_tryon_image(
            person_image_bytes=person_image_bytes,
            garment_image_bytes=garment_image_bytes,
        )
    except Exception as generation_error:
        # Log the error on the server (we'll see this in the terminal)
        print(f"[ERROR] Generation failed: {generation_error}")
        raise HTTPException(
            status_code=500,
            detail=f"Image generation failed: {str(generation_error)}"
        )

    # ── Return the image ──────────────────────────────────────────────────────
    # Response() lets us return raw bytes with a custom content type.
    # media_type="image/png" tells the browser (and Node.js) that
    # the response body is a PNG image file, not JSON text.
    return Response(
        content=result_image_bytes,
        media_type="image/png",
    )


# ── Run the server directly (for development) ─────────────────────────────────
# This block runs only when you execute: python main.py
# In production, you'd use: uvicorn main:app --port 8000
if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",   # Listen on all network interfaces
        port=8000,
        reload=True,       # Auto-restart when code changes
    )
