"""
app/main.py

Entry point for the VirtualFit AI Service (Phase 4 — Gemini Integration).

How to start:
    uvicorn app.main:app --reload --port 8000

API Documentation (auto-generated by FastAPI):
    http://localhost:8000/docs     ← interactive
    http://localhost:8000/redoc   ← alternative

Endpoints registered:
    GET  /health         — health check
    POST /generate       — backward-compat (returns raw PNG for Node.js)
    POST /api/try-on     — new JSON endpoint per spec
    GET  /output/{name}  — serve generated images for /api/try-on callers
"""

import logging
import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from app.config import settings
from app.routes.tryon import router as tryon_router
from app.utils.cleanup import cleanup_all_temp
from app.services.engines.fashn_engine import fashn_engine

# ── Logging setup ─────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


# ── Application lifespan ──────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs on startup and shutdown.

    Startup:
        - Log configuration summary.
        - Create temp directories.
        - Run initial cleanup of any stale files from a previous session.

    Shutdown:
        - Nothing needed for this demo.
    """
    # Startup
    logger.info("=" * 60)
    logger.info("VirtualFit AI Service — FASHN API Integration")
    logger.info("=" * 60)
    logger.info("Model:          %s", settings.FASHN_MODEL)
    logger.info("Resolution:     %s", settings.FASHN_RESOLUTION)
    logger.info("Gen Mode:       %s", settings.FASHN_GENERATION_MODE)
    logger.info("Upload folder:  %s", settings.UPLOAD_FOLDER)
    logger.info("Output folder:  %s", settings.OUTPUT_FOLDER)
    logger.info("File expiry:    %ds", settings.TEMP_IMAGE_EXPIRY)
    logger.info("API key set:    %s", bool(settings.FASHN_API_KEY))
    
    if not settings.FASHN_API_KEY:
        logger.error("FATAL: FASHN_API_KEY is not set.")
        sys.exit(1)
    logger.info("Docs:           http://%s:%d/docs", settings.HOST, settings.PORT)
    logger.info("=" * 60)

    # Ensure temp directories exist
    upload_path = settings.get_upload_path()
    output_path = settings.get_output_path()
    if not upload_path.exists():
        logger.error("FATAL: Upload directory could not be created/accessed.")
        sys.exit(1)
    if not output_path.exists():
        logger.error("FATAL: Output directory could not be created/accessed.")
        sys.exit(1)

    # Clean up stale files from previous runs
    cleanup_all_temp(upload_path, output_path, settings.TEMP_IMAGE_EXPIRY)

    yield

    # Shutdown
    logger.info("VirtualFit AI Service shutting down.")
    logger.info("Closing FASHN HTTP client...")
    await fashn_engine.client.aclose()
    logger.info("Shutdown complete.")


# ── FastAPI application ───────────────────────────────────────────────────────
app = FastAPI(
    title="VirtualFit AI Service",
    description=(
        "FASHN Try-On API Gateway.\n\n"
        "Accepts a person photo + garment photo and returns a photorealistic "
        "virtual try-on image generated by FASHN."
    ),
    version="4.0.0",
    lifespan=lifespan,
)

# ── Static file serving ───────────────────────────────────────────────────────
# Serve the generated images so /api/try-on callers can fetch by URL.
# We mount AFTER ensuring the directory exists (done in lifespan).
# We use a lazy mount pattern to handle the case where the folder
# doesn't exist yet at import time.
@app.on_event("startup")
async def mount_static():
    output_path = settings.get_output_path()
    app.mount(
        "/output",
        StaticFiles(directory=str(output_path)),
        name="output",
    )


# ── Routes ─────────────────────────────────────────────────────────────────────
# Register the try-on routes.
# This adds /generate and /api/try-on to the app.
app.include_router(tryon_router)


# ── Health check ───────────────────────────────────────────────────────────────
@app.get("/health", tags=["Health"])
async def health_check():
    """
    GET /health

    Returns service status and configuration summary.
    Used by Node.js to verify the AI service is available.

    Test with:
        curl http://localhost:8000/health
    """
    return {
        "status": "ok",
        "service": "VirtualFit AI Service",
        "phase": "Phase 4 — Gemini Integration",
        "provider": settings.AI_PROVIDER,
        "model": settings.GEMINI_MODEL,
        "gemini_configured": bool(settings.GEMINI_API_KEY),
    }


# ── Run directly (development only) ───────────────────────────────────────────
# In production (or normal dev), use:  uvicorn app.main:app --reload --port 8000
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "app.main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=True,
    )
